function topNode = run_task(location, blockSequence)
%% function [mainTreeNode, datatub] = run_task(location)
%
% run_task = Single Change Point Dots
%
% This function configures, initializes, runs, and cleans up a SingleCP_DotsReversal
%  experiment 
%
% 11/28/18   aer wrote it

%% ---- Clear 
clear globals

%% ---- Configure experiment based on location
%
%   locations are 'pilot', 'office', 'short', 'tutorial'
%
% UIs:
%  'dotsReadableEyeEyelink'
%  'dotsReadableEyePupilLabs'
%  'dotsReadableEyeEOG'
%  'dotsReadableHIDKeyboard'
%  'dotsReadableEyeMouseSimulator'
%  'dotsReadableHIDButtons'
%  'dotsReadableHIDGamepad'

switch location
    case {'office'}
        arglist = { ...
            'taskSpecs',            {'Tut1' 6}, ...%{'Quest' 50 'SN' 50 'AN' 50}, ...
            'trialFolder',          'Blocks003/', ...  % folder where trial generation data resides
            'readables',            {'dotsReadableHIDGamepad'}, ...
            'deactivateConsoleStatus', false, ...
            'recordDotsPositions',  false, ...
            'displayIndex',         1, ... % 0=small, 1=main, 2=other screen
            'remoteDrawing',        false, ...
            'sendTTLs',             false, ...
            'showFeedback',         0, ... % timeout for feedback
            'showSmileyFace',       0, ... % timeout for smiley face on correct target
        };
    
    case {'short'}
        arglist = { ...
            'taskSpecs',            { ...
%                                     'Tut1', 6, ...
%                                     'Quest', 15, ...
                                    'Tut2', 1%, ...
%                                     'Block2', 1, ...
%                                     'Tut3', 10, ...
%                                     'Block3', 5, ...
%                                     'Block4', 5, ...
%                                     'Block5', 5, ...
%                                     'Block6', 5, ...
%                                     'Block7', 5, ...
%                                     'Block8', 5, ...
%                                     'Block9', 5, ...
%                                     'Block10', 5, ...
%                                     'Block11', 5, ...
                                    }, ...%{'Quest' 50 'SN' 50 'AN' 50}, ...
            'trialFolder',          'Blocks003/', ...  % folder where trial generation data resides
            'readables',            {'dotsReadableHIDGamepad'}, ...
            'deactivateConsoleStatus', false, ...
            'recordDotsPositions',  false, ...
            'displayIndex',         2, ... % 0=small, 1=main, 2=other screen
            'remoteDrawing',        false, ...
            'sendTTLs',             false, ...
            'showFeedback',         0, ... % timeout for feedback
            'showSmileyFace',       0, ... % timeout for smiley face on correct target
        };
        
    case {'pilot'}
        arglist = { ...
            'taskSpecs',            blockSequence, ...%{'Quest' 50 'SN' 50 'AN' 50}, ...
            'trialFolder',          'Blocks003/', ...  % folder where trial generation data resides
            'readables',            {'dotsReadableHIDGamepad'}, ...
            'deactivateConsoleStatus', true, ...  % if true, trial by trial status not shown in console
            'recordDotsPositions',  true, ...
            'displayIndex',         2, ... % 0=small, 1=main, 2=other screen
            'remoteDrawing',        false, ...
            'sendTTLs',             false, ...
            'showFeedback',         0, ... % timeout for feedback
            'showSmileyFace',       0, ... % timeout for smiley face on correct target
        };
        
    case {'tutorial'}
        arglist = { ...
            'taskSpecs',            {'CP' 10}, ...%{'Quest' 50 'SN' 50 'AN' 50}, ...
            'probCPs',              .5, ... %this vector should be as long as there are task nodes.
            'readables',            {'dotsReadableHIDKeyboard'}, ...
            'displayIndex',         2, ... % 0=small, 1=main, 2=other screen
            'remoteDrawing',        false, ...
            'sendTTLs',             false, ...
            'showFeedback',         0.5, ... % timeout for feedback
            'showSmileyFace',       0.5, ... % timeout for smiley face on correct target
        };
end

%% ---- Call the configuration routine
%
topNode = configure_task(arglist{:});

%% ---- Run it!
%
topNode.run();
